### ISSUE TITLE
Will like to add the profile pic of project admin in the read me 

### ISSUE THREAD

**Issue by rohank2502** [Swarnimashukla/Automatic-attendance-management-system#56] opened 2021-03-12 11:32 UTC
I will like to add the profile picture in place of just name this will help us in making impression over the user who read the read me file !!

**Comment by Dimple115** [comment] 2021-03-13 09:42
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by Simar05519** [comment] 2021-03-13 15:27
I want to work on this issue. Please assign to me.

**Comment by bhubesh757** [comment] 2021-03-13 16:00
#29  this appears to be a duplicate of #29 . So, I am going to close this issue . @Simar05519  @rohank2502  @Dimple115 Feel free to contribute to other issues or create new issues

**Closed** 2021-03-13 16:43 UTC
Labels: duplicate
